### ISSUE TITLE
Manually setting default gateway/router IP

### ISSUE THREAD

**Issue by MCWithMC** [smithy212000/PortMiner#1]
Would be nice as I use PDANet and default gateway is set to the phone, rather than the router, thus the software doesn't work. PDANet is the only way I get internet.
EDIT: whoops, almost forgot to say thanks.

**Comment by smithy212000** [comment]
I'll look into making this soon

**Comment by smithy212000** [comment]
Not sure if I'd be able to do this currently as the library used doesn't look like it supports this, but maybe someday it will hopefully.
