### ISSUE TITLE
Running mods

### ISSUE THREAD

**Issue by jedimatt** [smithy212000/PortMiner#25]
I had an issue when trying to run a modded server(curse forge to be exact) I was wondering if this is not supported of if there is something else I have to do
P.S don’t have access to the actual error codes that popped up right now

**Comment by Trollneffer** [comment]
I've been testing this software for a while, what I recommend you do is, grab a fresh portminer and proceeded to integrate it together, it acts like a wrapper in my sense, and somehow it works without an issue.

**Comment by jedimatt** [comment]
Little confused what you mean by this

**Comment by jedimatt** [comment]
![FCEEBA27-813B-4AB5-9072-D0915DE8FA5A](https://user-images.githubusercontent.com/62773884/77831484-dde88600-7105-11ea-91f1-958ad07177d2.jpeg)
This is what happens when I try to run it

**Comment by jedimatt** [comment]
Apparently not a PortMiner issue but instead something else
