### ISSUE TITLE
Why, just why.

### ISSUE THREAD

**Issue by soshimee** [smithy212000/PortMiner#30]
Usually, if you can't port forward, you also can't enable UPnP, which is how you open the ports without the admin page.

**Comment by smithy212000** [comment]
UPnP is enabled on practically all routers by default. It's how p2p clients and various other games work. It clearly helps many people create servers that work already, so that's why.

**Comment by soshimee** [comment]
It is disabled for default for me, and no admin page. It was disabled on the last router that had admin page too.

**Comment by smithy212000** [comment]
In that case you'd have to enable it through the admin page, but this is for the **majority** of people that have already got UPnP enabled and can't or don't wish to port forward.

**Comment by soshimee** [comment]
Admin page, admin page, no admin page for me.
