### ISSUE TITLE
Where is the portminer.properties?

### ISSUE THREAD

**Issue by PDAleksa** [smithy212000/PortMiner#9]
I'm wanting to use this application for my TF2 server but i can not seem to find the portminer.properties file. I only have the jar file and the license.

**Comment by partyp770** [comment]
It's tucked away in the Appdata folder. Open a run prompt by pressing the Windows key + R. Then, type %appdata%. Then, press P until the Portminer folder is highlighted, and open it.

**Comment by toastom** [comment]
Hello! I'm trying to run this on a Raspberry Pi, which runs a version of Debian Linux. Where would the portminer.properties file be in this case?
